name: Build Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: beiyuouo/readme-action@latest
        with:
          blog_rss_link: https://blog.bj-yan.top/index.xml
          blog_limit: 5
          blog_time_format: "%a, %d %b %Y %H:%M:%S %z"
          douban_name: 179948994
          douban_limit: 5
          commit_message: Updated social rss by social-readme
          time_zone: "Asia/Shanghai"

  # update-wakatime:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: zylele/waka-readme@master
  #       with:
  #         SHOW_TITLE: true
  #         WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
